---
name: alphabeta
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: Sélectionner l’environnement
        required: true
        default: alpha
jobs:
  csv_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - alpha
          - beta
        python-version:
          - 3.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          
          python -m pip install --upgrade pip

          pip install pandas  # ou toute autre dépendance nécessaire
      - name: Run Python script for ${{ matrix.env }}
        run: |
          
          if [ "${{ matrix.env }}" == "alpha" ]; then

            python scripts/alpha.py

          elif [ "${{ matrix.env }}" == "beta" ]; then

            python scripts/beta.py

          fi
